# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
# Mod Properties
mod_version=2.5.2
maven_group=blade.addon
archives_base_name=blade-addons
# Dependencies
fabric_api_version=0.152.1+26.1.2
# I love dependencies sometimes breaking
practical_config=902a663c1b6c8917d02f12b7608eb373a9d3c1f3
modmenu_version=18.0.0-beta.1
hypixel_api_version=1.0.2
dev_auth_version=1.2.2
