package blade.addon;

import blade.addon.features.dungeon.AutoRequeue;
import blade.addon.features.dungeon.ChestCounter;
import blade.addon.features.dungeon.RunStartValidator;
import blade.addon.features.dungeon.ExplosiveShot;
import blade.addon.features.dungeon.HidePlayers;
import blade.addon.features.dungeon.ItemHighlight;
import blade.addon.features.dungeon.KeyNotifier;
import blade.addon.features.dungeon.LeapMessage;
import blade.addon.features.dungeon.SecretSpawnTimer;
import blade.addon.features.dungeon.WarpCooldown;
import blade.addon.features.dungeon.f7.BossWaypoints;
import blade.addon.features.dungeon.f7.CrystalSpawn;
import blade.addon.features.dungeon.f7.DistanceToLedge;
import blade.addon.features.dungeon.f7.DragSpawnTimer;
import blade.addon.features.dungeon.f7.PillarExplode;
import blade.addon.features.dungeon.f7.PredevTimer;
import blade.addon.features.dungeon.f7.RelicTimer;
import blade.addon.features.dungeon.f7.StormTickTimer;
import blade.addon.features.dungeon.f7.invincibility.InvincibilityTimer;
import blade.addon.features.dungeon.f7.location.LocationNotifier;
import blade.addon.features.dungeon.f7.location.PositionMessages;
import blade.addon.features.dungeon.f7.terms.GoldorTickTimer;
import blade.addon.features.dungeon.f7.terms.LeapNotification;
import blade.addon.features.dungeon.f7.terms.MelodyWarning;
import blade.addon.features.dungeon.f7.terms.Pre4Notifier;
import blade.addon.features.dungeon.f7.terms.TermStartTimer;
import blade.addon.features.highlight.MimicHighlight;
import blade.addon.features.highlight.MobHighlight;
import blade.addon.features.highlight.SheepHighlight;
import blade.addon.features.item.DropAnimation;
import blade.addon.features.other.CompactHoppity;
import blade.addon.features.other.DianaNotifier;
import blade.addon.features.other.KickedTimer;
import blade.addon.features.other.PracticeSS;
import blade.addon.features.other.RagDisplay;
import blade.addon.features.other.SelectedPet;
import blade.addon.utils.Commands;
import blade.addon.utils.Debug;
import blade.addon.utils.Keybinds;
import blade.addon.utils.Location;
import blade.addon.utils.Scheduler;
import blade.addon.utils.config.Config;
import blade.addon.utils.config.FolderUtility;
import blade.addon.utils.config.components.Components;
import blade.addon.utils.config.values.Buttons;
import blade.addon.utils.dungeon.DungeonClass;
import blade.addon.utils.dungeon.Phase;
import blade.addon.utils.dungeon.Section;
import blade.addon.utils.events.CustomEvents;
import net.fabricmc.api.ModInitializer;

public class Bladeaddons implements ModInitializer {
    @Override
    public void onInitialize() {
        FolderUtility.init();
        Components.init();
        Buttons.init();
        Config.manager.load();
        Keybinds.init();
        CustomEvents.init();
        Commands.init();
        Debug.init();
        Location.init();
        Phase.init();
        Section.init();
        DungeonClass.init();
        StormTickTimer.init();
        GoldorTickTimer.init();
        TermStartTimer.init();
        PositionMessages.init();
        InvincibilityTimer.init();
        WarpCooldown.init();
        LeapMessage.init();
        ExplosiveShot.init();
        RunStartValidator.init();
        HidePlayers.init();
        CrystalSpawn.init();
        KeyNotifier.init();
        RelicTimer.init();
        AutoRequeue.init();
        MobHighlight.init();
        ChestCounter.init();
        Scheduler.init();
        SecretSpawnTimer.init();
        DistanceToLedge.init();
        ItemHighlight.init();
        BossWaypoints.init();
        DianaNotifier.init();
        DragSpawnTimer.init();
        SelectedPet.init();
        LocationNotifier.init();
        PredevTimer.init();
        KickedTimer.init();
        Pre4Notifier.init();
        PillarExplode.init();
        MelodyWarning.init();
        RagDisplay.init();
        LeapNotification.init();
        PracticeSS.init();
        CompactHoppity.init();
        DropAnimation.init();
        MimicHighlight.init();
        SheepHighlight.init();
    }
}