package blade.addon;

import blade.addon.features.dungeon.*;
import blade.addon.features.dungeon.f7.BossWaypoints;
import blade.addon.features.dungeon.f7.PredevTimer;
import blade.addon.features.dungeon.f7.RelicTimer;
import blade.addon.features.dungeon.f7.StormLBTimer;
import blade.addon.features.dungeon.f7.dragons.DragSpawnTimer;
import blade.addon.features.dungeon.f7.dragons.DragonHealth;
import blade.addon.features.dungeon.f7.dragons.DragonTracer;
import blade.addon.features.dungeon.f7.invincibility.InvincibilityDuration;
import blade.addon.features.dungeon.f7.invincibility.InvincibilityTimer;
import blade.addon.features.dungeon.f7.invincibility.MaskHighlight;
import blade.addon.features.dungeon.f7.location.LocationNotifier;
import blade.addon.features.dungeon.f7.location.PositionMessages;
import blade.addon.features.dungeon.f7.maxor.CrystalSpawn;
import blade.addon.features.dungeon.f7.maxor.MaxorStun;
import blade.addon.features.dungeon.f7.maxor.MaxorTickTimer;
import blade.addon.features.dungeon.f7.storm.DistanceToLedge;
import blade.addon.features.dungeon.f7.storm.PillarExplode;
import blade.addon.features.dungeon.f7.storm.StormTickTimer;
import blade.addon.features.dungeon.f7.terms.*;
import blade.addon.features.filter.Filters;
import blade.addon.features.highlight.*;
import blade.addon.features.item.*;
import blade.addon.features.notifications.Notifications;
import blade.addon.features.other.*;
import blade.addon.features.sound.BonzoSound;
import blade.addon.features.sound.TubaSound;
import blade.addon.utils.Commands;
import blade.addon.utils.Keybinds;
import blade.addon.utils.Location;
import blade.addon.utils.Scheduler;
import blade.addon.utils.config.Config;
import blade.addon.utils.config.FolderUtility;
import blade.addon.utils.config.components.Components;
import blade.addon.utils.config.values.Buttons;
import blade.addon.utils.data.EntityUtil;
import blade.addon.utils.data.PartyUtil;
import blade.addon.utils.debug.Debug;
import blade.addon.utils.dungeon.DungeonClass;
import blade.addon.utils.dungeon.Phase;
import blade.addon.utils.dungeon.Section;
import blade.addon.utils.events.CustomEvents;
import blade.addon.utils.rendering.RenderingEvents;
import net.fabricmc.api.ModInitializer;

public class Bladeaddons implements ModInitializer {
    @Override
    public void onInitialize() {
        FolderUtility.init();
        Components.init();
        Buttons.init();
        try {
            Config.manager.load();
        }catch (NullPointerException err) {}
        Keybinds.init();
        CustomEvents.init();
        Commands.init();
        Debug.init();
        Location.init();
        Phase.init();
        Section.init();
        DungeonClass.init();

        PartyUtil.init();
        EntityUtil.init();

        RenderingEvents.init();

        StormTickTimer.init();
        GoldorTickTimer.init();
        TermStartTimer.init();
        PositionMessages.init();
        InvincibilityTimer.init();
        WarpCooldown.init();
        LeapMessage.init();
        ExplosiveShot.init();
        RunStartValidator.init();
        HidePlayers.init();
        CrystalSpawn.init();
        KeyNotifier.init();
        RelicTimer.init();
        AutoRequeue.init();
        MobHighlight.init();
        ChestCounter.init();
        Scheduler.init();
        SecretSpawnTimer.init();
        DistanceToLedge.init();
        ItemHighlight.init();
        BossWaypoints.init();
        DianaNotifier.init();
        DragSpawnTimer.init();
        SelectedPet.init();
        LocationNotifier.init();
        PredevTimer.init();
        KickedTimer.init();
        DeviceNotifier.init();
        PillarExplode.init();
        MelodyWarning.init();
        RagDisplay.init();
        LeapNotification.init();
        PracticeSS.init();
        CompactHoppity.init();
        DropAnimation.init();
        MimicHighlight.init();
        SheepHighlight.init();
        Notifications.init();
        BatHighlight.init();
        WitherHighlight.init();
        InvincibilityDuration.init();
        TeammateHighlight.init();
        SectionProgress.init();
        BonzoSound.init();
        QuizTimer.init();
        Filters.init();
        DragonHealth.init();
        MaxorStun.init();
        ArrowSwapper.init();
        StarCountHighlight.init();
        MaskHighlight.init();
        ItemRarityHighlight.init();
        ProtectItem.init();
        SelectedPetHighlight.init();
        SearchBar.init();
        TubaSound.init();
        SectionCompletion.init();
        MaxorTickTimer.init();
        BloodNotifier.init();
        CurrentSection.init();
        DragonTracer.init();
        ReaperDisplay.init();
        StormLBTimer.init();
        DeathMessage.init();
        BlockPetMenu.init();
        ToolTip.init();
    }
}